[project]
name = "market-simulator"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.1",
    "pandas>=2.3.1",
    "plotly>=6.2.0",
    "requests>=2.32.4",
    "ta>=0.11.0",
]

[dependency-groups]
lint = ["pyright>=1.1.397", "ruff>=0.11.0"]
